Repository mobi-community/mobi-ttak-kong, pull requests merged in 2023-10, with the labels that each got.

#6 #1 렌딩페이지 퍼블리싱 완료
  public/image/emoji-bbiyak.png
  public/image/emoji-diamond.png
  public/image/emoji-dizzy.png
  public/image/emoji-nerd.png
  public/image/emoji-sad.png
  public/image/emoji-smile.png
  public/image/emoji-thinking.png
  public/image/icon-beans.png
  public/image/intro-bg1.webp
  public/image/intro-bg2.webp
  public/image/intro-screen1.png
  public/image/intro-screen2.png
  public/image/intro-screen3.png
  public/image/logo-black.png
  public/image/logo-white.png
  public/image/next.svg
  public/image/testlogo.png
  src/app/intro/_components/CarouselButton/CarouselButton.tsx
  src/app/intro/_components/CarouselButton/CarouselButton.type.ts
  src/app/intro/_components/CarouselButton/index.ts
  src/app/intro/_components/IntroSectionFirst/IntroSectionFirst.tsx
  src/app/intro/_components/IntroSectionFirst/_components/InfoCard/InfoCard.tsx
  src/app/intro/_components/IntroSectionFirst/_components/InfoCard/index.ts
  src/app/intro/_components/IntroSectionFirst/_components/InfoCard/infoCard.types.ts
  src/app/intro/_components/IntroSectionFirst/_components/index.ts
  src/app/intro/_components/IntroSectionFirst/index.ts
  src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
  src/app/intro/_components/IntroSectionSecond/_components/ImageCardPair/ImageCardPair.tsx
  src/app/intro/_components/IntroSectionSecond/_components/ImageCardPair/ImageCardPair.type.ts
  src/app/intro/_components/IntroSectionSecond/_components/ImageCardPair/index.ts
  src/app/intro/_components/IntroSectionSecond/_components/StepCard/StepCard.tsx
  src/app/intro/_components/IntroSectionSecond/_components/StepCard/index.ts
  src/app/intro/_components/IntroSectionSecond/_components/index.ts
  src/app/intro/_components/IntroSectionSecond/index.ts
  src/app/intro/_components/IntroSectionSecond/introSectionSecond.type.ts
  src/app/intro/_components/IntroSectionThird/IntroSectionThird.tsx
  src/app/intro/_components/IntroSectionThird/index.ts
  src/app/intro/_components/index.ts
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Button/Button.tsx
  src/components/Header/Header.tsx
  src/components/Header/_components/IntroHeader/IntroHeader.tsx
  src/components/Header/_components/IntroHeader/index.ts
  src/components/Nav/Nav.tsx
  src/components/Nav/index.ts
  src/components/index.ts
  src/config/main.ts
  src/constants/main.ts
  src/constants/sectionFirst.constants.ts
  src/constants/sectionSecond.constants.ts
  src/hooks/useSmoothScroll.ts
  src/styles/global.css
  tailwind.config.ts
Labels: publishing

#8 #2 메인 페이지 퍼블리싱 완료
  package.json
  public/image/study-icon.png
  src/app/_components/SelectCard/SelectCard.tsx
  src/app/_components/SelectCard/SelectCard.type.ts
  src/app/_components/SelectCard/index.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/favicon.ico
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/constants/login.constants.ts
  src/constants/main.constants.ts
  tailwind.config.ts
  yarn.lock
Labels: publishing

#7 #4 전역 및 스터디 페이지에서 사용될 공용 컴포넌트를 추가합니다.
  package.json
  src/app/study/_components/QuestionContainer/QuestionContainer.tsx
  src/app/study/_components/QuestionContainer/QuestionContainer.types.ts
  src/app/study/_components/QuestionContainer/index.ts
  src/app/study/_components/index.ts
  src/app/study/create/_step/_components/InnerSection/InnerSection.tsx
  src/app/study/create/_step/_components/InnerSection/InnerSection.types.ts
  src/app/study/create/_step/_components/InnerSection/index.ts
  src/app/study/create/_step/_components/LevelCard/LevelCard.tsx
  src/app/study/create/_step/_components/LevelCard/LevelCard.types.ts
  src/app/study/create/_step/_components/LevelCard/index.ts
  src/app/study/create/_step/_components/NextStepButton/NextStepButton.tsx
  src/app/study/create/_step/_components/NextStepButton/NextStepButton.types.ts
  src/app/study/create/_step/_components/NextStepButton/index.ts
  src/app/study/create/_step/_components/index.ts
  src/components/Counter/Counter.tsx
  src/components/Counter/Counter.types.ts
  src/components/Counter/index.ts
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/components/Input/index.ts
  src/components/Progress/Progress.tsx
  src/components/Progress/Progress.types.ts
  src/components/Progress/index.ts
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/index.ts
  src/components/TextArea/Textarea.tsx
  src/components/TextArea/index.ts
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/constants/level.constants.ts
  src/constants/studyFields.constants.ts
  src/types/index.ts
  src/types/level.types.ts
  yarn.lock
Labels: publishing

#9 #3 매칭 페이지, 마이 스터디 페이지 퍼블리싱 완료
  public/image/default-profile-image.png
  public/image/level-image.png
  public/image/matching-loading.gif
  src/app/matching/_components/MatchingCard/MatchingCard.tsx
  src/app/matching/_components/MatchingCard/MatchingCard.type.ts
  src/app/matching/_components/MatchingCard/index.ts
  src/app/matching/_components/MatchingLoading/MatchingLoading.tsx
  src/app/matching/_components/MatchingLoading/index.ts
  src/app/matching/_components/NoMatchingCard/NoMatchingCard.tsx
  src/app/matching/_components/NoMatchingCard/index.ts
  src/app/matching/_components/index.ts
  src/app/matching/page.tsx
  src/app/mystudy/applied/[postId]/StudyAppliedDetailPage.type.ts
  src/app/mystudy/applied/[postId]/page.tsx
  src/app/mystudy/applied/_components/StudyAppliedCard/StudyAplliedCardProps.ts
  src/app/mystudy/applied/_components/StudyAppliedCard/StudyAppliedCard.tsx
  src/app/mystudy/applied/_components/StudyAppliedCard/index.ts
  src/app/mystudy/applied/_components/index.ts
  src/app/mystudy/applied/page.tsx
  src/app/mystudy/created/_components/StudyCreatedCard/StudyCreatedCard.tsx
  src/app/mystudy/created/_components/StudyCreatedCard/StudyCreatedCard.type.ts
  src/app/mystudy/created/_components/StudyCreatedCard/index.ts
  src/app/mystudy/created/_components/index.ts
  src/app/mystudy/created/page.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/constants/index.ts
  src/constants/matchingLoading.constants.ts
  src/constants/studyCreated.constants.ts
  tailwind.config.ts
Labels: publishing

#11 #10 Next Auth로 로그인기능을 구현했습니다.
  .env.example
  public/image/naver-logo.svg.png
  public/image/next.svg
  public/vercel.svg
  src/app/_components/LoginModal/LoginModal.tsx
  src/app/_components/LoginModal/LoginModal.type.ts
  src/app/_components/LoginModal/_components/NaverSignInOutButton.tsx
  src/app/_components/LoginModal/_components/NaverSignInOutButton.type.ts
  src/app/_components/LoginModal/_components/index.ts
  src/app/_components/LoginModal/index.ts
  src/app/_components/SelectCard/SelectCard.tsx
  src/app/_components/index.ts
  src/app/api/auth/[...nextauth]/AuthSession.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/intro/_components/IntroSectionSecond/_components/ImageCardPair/ImageCardPair.type.ts
  src/app/intro/_components/IntroSectionThird/IntroSectionThird.tsx
  src/app/intro/_components/IntroSectionThird/IntroSectionThird.type.ts
  src/app/intro/_components/IntroSectionThird/index.ts
  src/app/intro/_components/index.ts
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/matching/_components/MatchingCard/MatchingCard.tsx
  src/app/matching/page.tsx
  src/app/mystudy/applied/page.tsx
  src/app/mystudy/created/page.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/components/Header/_components/IntroHeader/IntroHeader.tsx
  src/components/Header/_components/IntroHeader/index.ts
  src/components/Header/index.ts
  src/components/IntroHeader/IntroHeader.tsx
  src/components/index.ts
Labels: feat

#12 #4 스터디 만들기 페이지 퍼블리싱을 일부분 마무리합니다.
  src/app/study/_step/CompletePage/CompletePage.constants.ts
  src/app/study/_step/CompletePage/CompletePage.tsx
  src/app/study/_step/CompletePage/CompletePage.types.ts
  src/app/study/_step/CompletePage/index.ts
  src/app/study/_step/Step1/Step1.tsx
  src/app/study/_step/Step1/index.ts
  src/app/study/_step/Step2/Step2.tsx
  src/app/study/_step/Step2/index.ts
  src/app/study/_step/Step3/Step3.tsx
  src/app/study/_step/Step3/index.ts
  src/app/study/_step/Step4/Step4.tsx
  src/app/study/_step/Step4/index.ts
  src/app/study/_step/_components/InnerSection/InnerSection.tsx
  src/app/study/_step/_components/InnerSection/InnerSection.types.ts
  src/app/study/_step/_components/InnerSection/index.ts
  src/app/study/_step/_components/LevelCard/LevelCard.tsx
  src/app/study/_step/_components/LevelCard/LevelCard.types.ts
  src/app/study/_step/_components/LevelCard/index.ts
  src/app/study/_step/_components/NextStepButton/NextStepButton.tsx
  src/app/study/_step/_components/NextStepButton/NextStepButton.types.ts
  src/app/study/_step/_components/NextStepButton/index.ts
  src/app/study/_step/_components/index.ts
  src/app/study/_step/_types/StepPage.type.ts
  src/app/study/_step/_types/index.ts
  src/app/study/_step/index.ts
  src/app/study/create/page.tsx
  src/components/Counter/Counter.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/index.ts
  src/components/ToggleGroup/ToggleGroup.tsx
  src/components/ToggleGroup/index.ts
  src/components/index.ts
  src/constants/level.constants.ts
Labels: publishing

#16 #15 스터디 만들기 Step1, Step2, Step3 유효성 검사를 적용합니다.
  package.json
  src/app/study/_step/Step1/Step1.tsx
  src/app/study/_step/Step2/Step2.tsx
  src/app/study/_step/Step3/Step3.tsx
  src/app/study/_step/_components/LevelCard/LevelCard.tsx
  src/app/study/_step/_components/LevelCard/LevelCard.types.ts
  src/app/study/_step/_components/NextStepButton/NextStepButton.types.ts
  src/app/study/_step/_schema/step.schema.ts
  src/components/Counter/Counter.tsx
  src/components/Counter/Counter.types.ts
  src/components/Select/Select.tsx
  src/components/Select/index.ts
  src/components/index.ts
  src/constants/studyFields.constants.ts
  src/types/index.ts
  src/types/studyFields.types.ts
  yarn.lock
Labels: feat

#17 #15 Step4 페이지 유효성 검사 적용했습니다.
  src/app/study/_step/Step2/Step2.tsx
  src/app/study/_step/Step4/Step4.tsx
Labels: feat

#20 #19 msw 환경 세팅을 마무리합니다.
  package.json
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/app/providers.tsx
  src/mocks/apis/index.ts
  src/mocks/apis/study.apis.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  yarn.lock
Labels: init

#22 #21 Storybook 환경 세팅을 마무리합니다.
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  package.json
  src/components/Button/Button.stories.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: init
